version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    env_file: ../.env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
    depends_on:
      - backend
